### PR TITLE
Make Hawk.Suave compatible with Suave 1.0

### PR DESCRIPTION
**Pull request by catlion**
Suave is now released version 1.0 and made a bit of changes in API and namespaces. I could not make test work in Windows, still investigating

### CODE REVIEW

**Comment by haf** [comment]
This is great! :+1: 

Awaiting your tests on Windows then. I believe they all pass on OS X.

**Comment by haf** [comment]
So why did you just close this?

**Comment by catlion** [comment]
35a79ef5a754dcd4c154fd9cc9be141ebc10f781 seem to do a better job of addressing the same problem. Also I'm experienced strange problem with this [test](https://github.com/logibit/logibit.hawk/blob/master/src/logibit.hawk.suave.tests/Hawk.fs#L79), the `setAuthHeader` function seemed to be applied twice. I'll check with fresh version and let you know if I'll find something.

**Comment by haf** [comment]
I see. Thanks, forgot I had also done it.

**Pull request closed without merging**
