### PR TITLE
Fixes in line with Suave API changes, and allow running tests in Visual Studio

### PR DESCRIPTION
**Pull request by treefrog00**

### CODE REVIEW

**Comment by haf** [comment]
Sweet!

Would you mind to create a logibit.hawk-vs2012.sln, to still support Xamarin Studio?

**Comment by treefrog00** [comment]
Can Xamarin Studio not cope with the new 2013 headers? Visual Studio 2012 can still open files with the new headers, as long as MinimumVisualStudioVersion is low enough.

**Comment by haf** [comment]
Let me check.

**Comment by haf** [comment]
Let's bump a minor for this change, yeah?

**Comment by haf** [comment]
Tests passing.

**Comment by haf** [comment]
Yes, it works, great! :)

**Comment by haf** [comment]
Done. https://github.com/logibit/logibit.hawk/releases =) Thanks Justin, looking forward to more nice PRs from you ;)

**Comment by haf** [comment]
Turns out that is _does_ accept it, but changes it back to 2012.

**Comment by treefrog00** [comment]
Hmm, never mind then! Btw I'm James not Justin!

**Comment by haf** [comment]
Sorry :p I was a bit confused yesterday evening.

**Pull request merged**
